# Generated by Django 3.2 on 2021-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='digits_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
