# Generated by Django 3.2 on 2021-04-19 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_number_digits_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='digits_quantity',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
