# Generated by Django 3.2 on 2021-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_alter_number_digits_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='digits_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
